name: Crash to Desktop
description: For issues that cause the game to crash to desktop (CTD)
title: "Country Affected - Short Description of Issue"
labels: Crash

body:
  - type: input
    id: OS
    attributes:
      label: Operating System
      placeholder: ex. Windows 11, macOS Monterey
    validations:
      required: true
  - type: input
    id: HOI4_version
    attributes:
      label: HOI4 version
      placeholder: Do NOT write latest version. ex. 1.11.7
    validations:
      required: true
  - type: input
    id: TNO_version
    attributes:
      label: TNO version
      placeholder: Do NOT write latest version. ex. 1.2.1b
    validations:
      required: true
  - type: input
    id: other_mods
    attributes:
      label: Do you have other mods in use?
      description: "Write none if you only have TNO enabled."
      placeholder: ex. The Moe Order
    validations:
      required: true
  - type: dropdown
    id: steam
    attributes:
      label: Were you using Steam?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    id: expansion
    attributes:
      label: Which major expansions do you NOT have?
      description: Click all expansions that you don't have.
      multiple: true
      options:
        - 'I have all'
        - 'MTG'
        - 'LAR'
        - 'NSB'
        - 'BBA'
        - 'AAT'
        - 'TOA'
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Files
      description: |
        Link(s) to any log files / save games that may help debug your issue.
        The most important ones are game.log and error.log
        Log files can be found under Documents\Paradox Interactive\Hearts of Iron IV\logs
        Save games can be found under Documents\Paradox Interactive\Hearts of Iron IV\save games
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the crash
      description: |
        A clear and concise description of what the crash looks like
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce / Cause of the crash
      description: Tell us how we can reproduce / fix this crash
      placeholder: |
        1. Go to ...  
        2. Click on ...  
        3. Scroll down to ...  
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
