name: Localization
about: For small issues related to spelling, grammar, and other typos. NOTE - If text is partially missing or absent entirely, please fill out a Bug issue type instead
title: Country Affected - Short Description of Issue
labels: Localization
assignees: ''

**Questions**

- HOI4 Version:
- TNO Version:
- Any other mods in use:

**List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):**


body:
  - type: input
    id: HOI4_version
    attributes:
      label: HOI4 version
      placeholder: Do NOT write latest version. ex. 1.11.7
    validations:
      required: true
  - type: input
    id: TNO_version
    attributes:
      label: TNO version
      placeholder: Do NOT write latest version. ex. 1.2.1b
    validations:
      required: true
  - type: input
    id: other_mods
    attributes:
      label: Do you have other mods in use?
      description: "Write none if you only have TNO enabled."
      placeholder: ex. Custom Country Paths Mod
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: List the loc issues below
      description: |
        List the Loc issues down below (preferably with screenshot attached below with event id / focus id shown):
      placeholder: 
        - [ ] 1. 
        (Screenshot here)
        - [ ] 2. 
        (Screenshot here)
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
